### ISSUE TITLE
Deprecated GPUBuffer.setSubData Apparently Broken Now

### ISSUE THREAD

**Issue by KTRosenberg** [austinEng/webgpu-samples#31] opened 2020-01-12 23:08 UTC
`GPUBuffer.setSubData` was removed from the spec a while ago, but it continued to work until at least the last time I posted about a WebGPU breakage, which was a few weeks ago. All of the examples that use `setSubData` no longer work, though the method does still exist. The triangle examples don't use the method, so they are fine.

It's unclear whether there will be any attempts to fix or replace `setSubData` since I believe the decision to deprecate was related to poor performance. (Maybe they're trying to re-implement it?)

If it's not fixed by the next version of Chrome or a few, it might be worth looking into some of the alternative ways of uploading buffer data.

This change log shows what the developers did to replace setSubData for a few use cases:
https://trac.webkit.org/changeset/246217/webkit

Here's some example code from the WebGPU design github repository:
https://github.com/gpuweb/gpuweb/blob/master/design/BufferOperations.md

I hope they're still thinking about how to get a higher level buffer upload function into the API, but for now these lower level functions do seem to work. I used them to fix my own example.

**Comment by austinEng** [comment] 2020-01-13 18:58
Thanks for the head's up this is a recent regression caused by https://dawn-review.googlesource.com/c/dawn/+/14780. It's been reverted and the fix should land in Canary in a few days.

As for buffer uploads, I think it's likely we'll have something similar to `setSubData` in addition to the mapping APIs, but the group is still discussing this.

**Comment by KTRosenberg** [comment] 2020-01-13 19:05
I see. Is that dawn repository the best place to watch for issues and API changes/examples? As you can probably tell, I'm trying to follow along with WebGPU development.

**Comment by kainino0x** [comment] 2020-01-13 19:15
https://github.com/gpuweb/gpuweb is the place to watch for specification development. Chromium development is somewhat scattered, but:

Mailing list (with occasional updates):
https://groups.google.com/g/dawn-graphics
Bugs:
https://crbug.com/?q=component%3ABlink%3EWebGPU%20OR%20component%3AInternals%3EGPU%3EDawn
https://crbug.com/dawn
Changes:
https://dawn-review.googlesource.com/
https://chromium-review.googlesource.com/q/file:webgpu

**Comment by KTRosenberg** [comment] 2020-01-13 19:39
Thanks for the links. The mailing list seems to be inaccessible, but might it be private?

**Comment by kainino0x** [comment] 2020-01-13 19:47
Sorry, bad link. Correct one: https://groups.google.com/forum/#!forum/dawn-graphics

**Comment by austinEng** [comment] 2020-03-23 19:51
This issue has been fixed for a while. Closing.

**Closed by austinEng** 2020-03-23 19:51 UTC
