### ISSUE TITLE
example MSAA broken

### ISSUE THREAD

**Issue by edap** [austinEng/webgpu-samples#22] opened 2019-10-11 14:39 UTC
Hello Austin, this example is broken https://austineng.github.io/webgpu-samples/#twoCubes

```
rotatingCube.ts:66 Uncaught (in promise) TypeError: Failed to execute 'createRenderPipeline' on 'GPUDevice': required member stencilBack is undefined.
    at Module.<anonymous> (rotatingCube.ts:66)
    at Generator.next (<anonymous>)
    at o (rotatingCube.js:1)
```

Also, the first one with the red triangle is working just when i load the page the first time.

I am on chrome 79.0.3928.4 (Official Build) dev (64-bit)

**Comment by austinEng** [comment] 2019-10-12 00:03
Hi @edap, I see you're using the Chrome Dev channel. Since WebGPU is under active development, we update the shape of the API fairly often. If you use Chrome Canary, you'll be more up-to-date with the latest changes.

I try to keep the samples up-to-date with Canary, so if you use Dev, things might break for a few days until it updates.

The specific issue you're seeing is happening because we changed the API such that `stencilBack` is no longer required and now has a default value.

Thanks for reporting this though. I plan to add a note on the main page to communicate this better :)

**Comment by edap** [comment] 2019-10-15 06:50
I see, thanks for your explanation.

**Comment by edap** [comment] 2019-10-15 07:20
Hello Austin, I have downloaded canary (Version 79.0.3941.4 (Official Build) canary (64-bit)) and I have enable the webgpu flag. The errors are gone but I see only the code on a black background. See picture in attachment. I am on mac. The first example with the red triangle works when reloading the page.

<img width="1260" alt="Screen Shot 2019-10-15 at 09 19 18" src="https://user-images.githubusercontent.com/161152/66809074-e9b40780-ef2c-11e9-890d-598501d037e4.png">

**Comment by austinEng** [comment] 2019-10-15 19:57
Hm, that's very strange. There are no errors at all in the console? Do the other examples work?

**Comment by edap** [comment] 2019-10-15 20:56
Ok, I think I can reproduce the bug consistently, and I think it is related to the `helloTriangleMSAA` example.
If I open google canary and I go to this url `https://austineng.github.io/webgpu-samples/#animometer` it works, I see the colored triangles. Same apply for `computeBoids`, `fractalCube`, `texturedCube`, `instancedCube`, `twoCubes`, `rotatingCube` and `helloTriangle`. As soon as I click on `helloTriangleMSAA` it looks like the browser tries to open another windows but it closes it immediately. The window does not show any animation(except some blinking white squares), as in the screenshot that I have posted yesterday. If I click on the previous examples, they do not work. The only way to get some of the examples working is to close canary and reopen it again from one of the working URL. If I open the browser and I load the page https://austineng.github.io/webgpu-samples/#helloTriangleMSAA id does not work, the screen is black.

**Comment by kainino0x** [comment] 2019-10-15 21:17
That definitely sounds like a GPU process crash. I'm guessing it's hardware specific because we haven't been able to reproduce it.

Could you share what Mac hardware you have?

**Comment by edap** [comment] 2019-10-16 07:07
I am on Mac OS "El Capitan", MacBook Pro (Retina, 13-inch, Mid 2014).
GPU Intel Iris 1536 MB.

**Comment by kainino0x** [comment] 2019-10-25 23:25
Austin suggested this could be related to a workaround we have in Dawn:
https://cs.chromium.org/chromium/src/third_party/dawn/src/dawn_native/metal/CommandBufferMTL.mm?l=820&rcl=04863c42beddde4b4e8a76884094101c0ba7e1cc

@Jiawei-Shao maybe you could look into this?

**Comment by Jiawei-Shao** [comment] 2019-10-28 07:10
Hi @kainino0x @austinEng, this workaround should only take effect when the level or array layer is not 0, so it should not affect this sample.

MacOS "EI Captian" is MacOS 10.11, but our bots are using at least 10.12, so I suspect maybe we are using some features that are not supported on that OS version.

I cannot reproduce this failure on a same type of  MacBook Pro (Retina, 13-inch, Mid 2014) or MacBook Pro (Retina, 15-inch, Mid 2015) with MacOS 10.14 and the latest Chrome Canary.

**Comment by kainino0x** [comment] 2019-10-31 20:57
@Jiawei-Shao, it turns out to be EmulateStoreAndMSAAResolve which needs to be applied [but isn't](https://cs.chromium.org/chromium/src/third_party/dawn/src/dawn_native/metal/DeviceMTL.mm?l=81&rcl=cdc22769d47487131c108db1b0ede32b7d28f1b8).

Specifically @Kangz wrapped it in `if (@available(macOS 10.12, *))` so we don't set the toggle if on 10.11.

Anyway, I'll just open a fix for this. Should be trivial.

**Comment by kainino0x** [comment] 2019-10-31 21:42
Since this is a Chrome/Dawn bug, closing this in favor of a bug I opened there:
https://bugs.chromium.org/p/dawn/issues/detail?id=253

**Closed by kainino0x** 2019-10-31 21:42 UTC

**Comment by kainino0x** [comment] 2019-10-31 21:44
@edap, thanks for the report! BTW, please consider updating your macOS version, as 10.11 is very old and has many graphics driver issues :)
