### ISSUE TITLE
Small UI bug on https://austin-eng.com/webgpu-samples/samples/helloTriangle#../../shaders/red.frag.wgsl

### ISSUE THREAD

**Issue by AntonioNoack** [austinEng/webgpu-samples#178] opened 2022-05-06 05:04 UTC
Hi,

I noticed a small bug on https://austin-eng.com/webgpu-samples/samples/helloTriangle#../../shaders/red.frag.wgsl :
When looking at the fragment shader source code, the very last line, and the one before it are laid on top of each other.

![image](https://user-images.githubusercontent.com/20659579/167070185-baf94b97-f7b5-4bec-abce-d1a6e63e7486.png)

About my setup:
Windows 10 Personal
Ryzen 5 2600, RX 580 8 GB, 32 GB DDR4
Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by austinEng** [comment] 2022-06-03 22:20
Duplicate of #156

**Closed by austinEng** 2022-06-03 22:21 UTC
